local M = {}

function M.setup(p, config)
  local hl = vim.api.nvim_set_hl
  local transparent = config.transparent_background
  local italic = config.enable_italic
  local disable_italic_comment = config.disable_italic_comment

  -- Helper for conditional background
  local bg0 = transparent and "NONE" or p.bg0
  local bg1 = transparent and "NONE" or p.bg1

  -- UI
  hl(0, "Normal", { fg = p.fg, bg = bg0 })
  hl(0, "Terminal", { fg = p.fg, bg = bg0 })
  hl(0, "EndOfBuffer", { fg = p.bg0, bg = bg0 })
  hl(0, "FoldColumn", { fg = p.grey, bg = bg1 })
  hl(0, "Folded", { fg = p.grey, bg = bg1 })
  hl(0, "SignColumn", { fg = p.fg, bg = bg1 })
  hl(0, "ToolbarLine", { fg = p.fg, bg = transparent and "NONE" or p.bg2 })
  hl(0, "ColorColumn", { bg = p.bg1 })
  hl(0, "Conceal", { fg = p.grey })
  hl(0, "Cursor", { reverse = true })
  hl(0, "vCursor", { link = "Cursor" })
  hl(0, "iCursor", { link = "Cursor" })
  hl(0, "lCursor", { link = "Cursor" })
  hl(0, "CursorIM", { link = "Cursor" })
  hl(0, "CursorColumn", { bg = p.bg1 })
  hl(0, "CursorLine", { bg = p.bg1 })
  hl(0, "LineNr", { fg = p.grey })
  hl(0, "CursorLineNr", { fg = p.fg, bg = p.bg1 })
  hl(0, "DiffAdd", { bg = p.diff_green })
  hl(0, "DiffChange", { bg = p.diff_blue })
  hl(0, "DiffDelete", { bg = p.diff_red })
  hl(0, "DiffText", { reverse = true })
  hl(0, "Directory", { fg = p.green })
  hl(0, "ErrorMsg", { fg = p.red, bold = true, underline = true })
  hl(0, "WarningMsg", { fg = p.yellow, bold = true })
  hl(0, "ModeMsg", { fg = p.fg, bold = true })
  hl(0, "MoreMsg", { fg = p.blue, bold = true })
  hl(0, "IncSearch", { fg = p.bg0, bg = p.bg_red })
  hl(0, "Search", { fg = p.bg0, bg = p.bg_green })
  hl(0, "MatchParen", { bg = p.bg4 })
  hl(0, "NonText", { fg = p.bg4 })
  hl(0, "Whitespace", { fg = p.bg4 })
  hl(0, "SpecialKey", { fg = p.bg4 })
  hl(0, "Pmenu", { fg = p.fg, bg = p.bg2 })
  hl(0, "PmenuSbar", { bg = p.bg2 })
  hl(0, "PmenuSel", { fg = p.bg0, bg = p.bg_green })
  hl(0, "WildMenu", { fg = p.bg0, bg = p.bg_green })
  hl(0, "PmenuThumb", { bg = p.grey })
  hl(0, "Question", { fg = p.yellow })
  hl(0, "SpellBad", { sp = p.red, undercurl = true })
  hl(0, "SpellCap", { sp = p.yellow, undercurl = true })
  hl(0, "SpellLocal", { sp = p.blue, undercurl = true })
  hl(0, "SpellRare", { sp = p.purple, undercurl = true })
  hl(0, "StatusLine", { fg = p.fg, bg = p.bg3 })
  hl(0, "StatusLineTerm", { fg = p.fg, bg = p.bg3 })
  hl(0, "StatusLineNC", { fg = p.grey, bg = p.bg1 })
  hl(0, "StatusLineTermNC", { fg = p.grey, bg = p.bg1 })
  hl(0, "TabLine", { fg = p.fg, bg = p.bg4 })
  hl(0, "TabLineFill", { fg = p.grey, bg = p.bg1 })
  hl(0, "TabLineSel", { fg = p.bg0, bg = p.bg_red })
  hl(0, "VertSplit", { fg = p.black })
  hl(0, "WinSeparator", { fg = p.black })
  hl(0, "Visual", { bg = p.bg3 })
  hl(0, "VisualNOS", { bg = p.bg3, underline = true })
  hl(0, "QuickFixLine", { fg = p.blue, bold = true })
  hl(0, "Debug", { fg = p.yellow })
  hl(0, "debugPC", { fg = p.bg0, bg = p.green })
  hl(0, "debugBreakpoint", { fg = p.bg0, bg = p.red })
  hl(0, "ToolbarButton", { fg = p.bg0, bg = p.bg_blue })

  -- Syntax
  hl(0, "Type", { fg = p.blue, italic = italic })
  hl(0, "Structure", { fg = p.blue, italic = italic })
  hl(0, "StorageClass", { fg = p.blue, italic = italic })
  hl(0, "Identifier", { fg = p.orange, italic = italic })
  hl(0, "Constant", { fg = p.orange, italic = italic })
  hl(0, "PreProc", { fg = p.red })
  hl(0, "PreCondit", { fg = p.red })
  hl(0, "Include", { fg = p.red })
  hl(0, "Keyword", { fg = p.red })
  hl(0, "Define", { fg = p.red })
  hl(0, "Typedef", { fg = p.red })
  hl(0, "Exception", { fg = p.red })
  hl(0, "Conditional", { fg = p.red })
  hl(0, "Repeat", { fg = p.red })
  hl(0, "Statement", { fg = p.red })
  hl(0, "Macro", { fg = p.purple })
  hl(0, "Error", { fg = p.red })
  hl(0, "Label", { fg = p.purple })
  hl(0, "Special", { fg = p.purple })
  hl(0, "SpecialChar", { fg = p.purple })
  hl(0, "Boolean", { fg = p.purple })
  hl(0, "String", { fg = p.yellow })
  hl(0, "Character", { fg = p.yellow })
  hl(0, "Number", { fg = p.purple })
  hl(0, "Float", { fg = p.purple })
  hl(0, "Function", { fg = p.green })
  hl(0, "Operator", { fg = p.red })
  hl(0, "Title", { fg = p.red, bold = true })
  hl(0, "Tag", { fg = p.orange })
  hl(0, "Delimiter", { fg = p.fg })
  hl(0, "Comment", { fg = p.grey, italic = not disable_italic_comment })
  hl(0, "SpecialComment", { fg = p.grey, italic = not disable_italic_comment })
  hl(0, "Todo", { fg = p.blue, italic = not disable_italic_comment })
  hl(0, "Ignore", { fg = p.grey })
  hl(0, "Underlined", { underline = true })

  -- Predefined highlight groups
  hl(0, "Fg", { fg = p.fg })
  hl(0, "Grey", { fg = p.grey })
  hl(0, "Red", { fg = p.red })
  hl(0, "Orange", { fg = p.orange })
  hl(0, "Yellow", { fg = p.yellow })
  hl(0, "Green", { fg = p.green })
  hl(0, "Blue", { fg = p.blue })
  hl(0, "Purple", { fg = p.purple })
  hl(0, "RedItalic", { fg = p.red, italic = italic })
  hl(0, "BlueItalic", { fg = p.blue, italic = italic })
  hl(0, "OrangeItalic", { fg = p.orange, italic = italic })

  -- Neovim Diagnostic API
  hl(0, "DiagnosticError", { fg = p.red })
  hl(0, "DiagnosticWarn", { fg = p.yellow })
  hl(0, "DiagnosticInfo", { fg = p.blue })
  hl(0, "DiagnosticHint", { fg = p.green })
  hl(0, "DiagnosticUnderlineError", { sp = p.red, undercurl = true })
  hl(0, "DiagnosticUnderlineWarn", { sp = p.yellow, undercurl = true })
  hl(0, "DiagnosticUnderlineInfo", { sp = p.blue, undercurl = true })
  hl(0, "DiagnosticUnderlineHint", { sp = p.green, undercurl = true })
  hl(0, "DiagnosticSignError", { fg = p.red, bg = bg1 })
  hl(0, "DiagnosticSignWarn", { fg = p.yellow, bg = bg1 })
  hl(0, "DiagnosticSignInfo", { fg = p.blue, bg = bg1 })
  hl(0, "DiagnosticSignHint", { fg = p.green, bg = bg1 })
  hl(0, "DiagnosticVirtualTextError", { fg = p.grey })
  hl(0, "DiagnosticVirtualTextWarn", { fg = p.grey })
  hl(0, "DiagnosticVirtualTextInfo", { fg = p.grey })
  hl(0, "DiagnosticVirtualTextHint", { fg = p.grey })
  hl(0, "DiagnosticFloatingError", { fg = p.red })
  hl(0, "DiagnosticFloatingWarn", { fg = p.yellow })
  hl(0, "DiagnosticFloatingInfo", { fg = p.blue })
  hl(0, "DiagnosticFloatingHint", { fg = p.green })

  -- Neovim health
  hl(0, "healthError", { link = "Red" })
  hl(0, "healthSuccess", { link = "Green" })
  hl(0, "healthWarning", { link = "Yellow" })

  -- LSP
  hl(0, "LspReferenceText", { underline = true })
  hl(0, "LspReferenceRead", { underline = true })
  hl(0, "LspReferenceWrite", { underline = true })
  hl(0, "LspSignatureActiveParameter", { fg = p.orange, bold = true })
  hl(0, "LspInfoBorder", { fg = p.grey })

  -- Treesitter
  hl(0, "@variable", { fg = p.fg })
  hl(0, "@variable.builtin", { fg = p.orange, italic = italic })
  hl(0, "@variable.parameter", { fg = p.orange })
  hl(0, "@variable.member", { fg = p.blue })
  hl(0, "@constant", { fg = p.orange })
  hl(0, "@constant.builtin", { fg = p.orange, italic = italic })
  hl(0, "@constant.macro", { fg = p.purple })
  hl(0, "@module", { fg = p.blue, italic = italic })
  hl(0, "@label", { fg = p.purple })
  hl(0, "@string", { link = "String" })
  hl(0, "@string.documentation", { link = "String" })
  hl(0, "@string.regexp", { fg = p.yellow })
  hl(0, "@string.escape", { fg = p.purple })
  hl(0, "@string.special", { fg = p.purple })
  hl(0, "@character", { link = "Character" })
  hl(0, "@character.special", { link = "SpecialChar" })
  hl(0, "@boolean", { link = "Boolean" })
  hl(0, "@number", { link = "Number" })
  hl(0, "@float", { link = "Float" })
  hl(0, "@type", { fg = p.blue, italic = italic })
  hl(0, "@type.builtin", { fg = p.blue, italic = italic })
  hl(0, "@type.definition", { fg = p.blue, italic = italic })
  hl(0, "@type.qualifier", { fg = p.red })
  hl(0, "@attribute", { fg = p.purple })
  hl(0, "@property", { fg = p.blue })
  hl(0, "@function", { fg = p.green })
  hl(0, "@function.builtin", { fg = p.green })
  hl(0, "@function.call", { fg = p.green })
  hl(0, "@function.macro", { fg = p.purple })
  hl(0, "@function.method", { fg = p.green })
  hl(0, "@function.method.call", { fg = p.green })
  hl(0, "@constructor", { fg = p.green })
  hl(0, "@operator", { fg = p.red })
  hl(0, "@keyword", { fg = p.red })
  hl(0, "@keyword.coroutine", { fg = p.red })
  hl(0, "@keyword.function", { fg = p.red })
  hl(0, "@keyword.operator", { fg = p.red })
  hl(0, "@keyword.import", { fg = p.red })
  hl(0, "@keyword.storage", { fg = p.red })
  hl(0, "@keyword.repeat", { fg = p.red })
  hl(0, "@keyword.return", { fg = p.red })
  hl(0, "@keyword.debug", { fg = p.red })
  hl(0, "@keyword.exception", { fg = p.red })
  hl(0, "@keyword.conditional", { fg = p.red })
  hl(0, "@keyword.directive", { fg = p.red })
  hl(0, "@keyword.directive.define", { fg = p.red })
  hl(0, "@punctuation.delimiter", { fg = p.grey })
  hl(0, "@punctuation.bracket", { fg = p.fg })
  hl(0, "@punctuation.special", { fg = p.purple })
  hl(0, "@comment", { link = "Comment" })
  hl(0, "@comment.documentation", { link = "Comment" })
  hl(0, "@comment.error", { fg = p.red })
  hl(0, "@comment.warning", { fg = p.yellow })
  hl(0, "@comment.note", { fg = p.blue })
  hl(0, "@comment.todo", { link = "Todo" })
  hl(0, "@markup.strong", { bold = true })
  hl(0, "@markup.italic", { italic = true })
  hl(0, "@markup.strikethrough", { fg = p.grey, strikethrough = true })
  hl(0, "@markup.underline", { underline = true })
  hl(0, "@markup.heading", { link = "Title" })
  hl(0, "@markup.quote", { fg = p.grey })
  hl(0, "@markup.math", { fg = p.purple })
  hl(0, "@markup.environment", { fg = p.purple })
  hl(0, "@markup.link", { fg = p.blue })
  hl(0, "@markup.link.label", { fg = p.blue })
  hl(0, "@markup.link.url", { underline = true })
  hl(0, "@markup.raw", { fg = p.green })
  hl(0, "@markup.list", { fg = p.red })
  hl(0, "@markup.list.checked", { fg = p.green })
  hl(0, "@markup.list.unchecked", { fg = p.grey })
  hl(0, "@diff.plus", { link = "diffAdded" })
  hl(0, "@diff.minus", { link = "diffRemoved" })
  hl(0, "@diff.delta", { link = "diffChanged" })
  hl(0, "@tag", { fg = p.green })
  hl(0, "@tag.attribute", { fg = p.blue })
  hl(0, "@tag.delimiter", { fg = p.grey })

  -- Diff
  hl(0, "diffAdded", { fg = p.green })
  hl(0, "diffRemoved", { fg = p.red })
  hl(0, "diffChanged", { fg = p.blue })
  hl(0, "diffOldFile", { fg = p.yellow })
  hl(0, "diffNewFile", { fg = p.orange })
  hl(0, "diffFile", { fg = p.purple })
  hl(0, "diffLine", { fg = p.grey })
  hl(0, "diffIndexLine", { fg = p.purple })

  -- Git signs
  hl(0, "GitSignsAdd", { fg = p.green, bg = bg1 })
  hl(0, "GitSignsChange", { fg = p.blue, bg = bg1 })
  hl(0, "GitSignsDelete", { fg = p.red, bg = bg1 })

  -- Telescope
  hl(0, "TelescopeBorder", { fg = p.grey })
  hl(0, "TelescopePromptBorder", { fg = p.grey })
  hl(0, "TelescopeResultsBorder", { fg = p.grey })
  hl(0, "TelescopePreviewBorder", { fg = p.grey })
  hl(0, "TelescopeMatching", { fg = p.green, bold = true })
  hl(0, "TelescopePromptPrefix", { fg = p.red })
  hl(0, "TelescopeSelection", { bg = p.bg3 })
  hl(0, "TelescopeSelectionCaret", { fg = p.red })

  -- nvim-cmp
  hl(0, "CmpItemAbbr", { fg = p.fg })
  hl(0, "CmpItemAbbrDeprecated", { fg = p.grey, strikethrough = true })
  hl(0, "CmpItemAbbrMatch", { fg = p.green, bold = true })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = p.green, bold = true })
  hl(0, "CmpItemKind", { fg = p.purple })
  hl(0, "CmpItemMenu", { fg = p.grey })

  -- nvim-tree
  hl(0, "NvimTreeNormal", { fg = p.fg, bg = bg0 })
  hl(0, "NvimTreeFolderIcon", { fg = p.blue })
  hl(0, "NvimTreeFolderName", { fg = p.green })
  hl(0, "NvimTreeOpenedFolderName", { fg = p.green })
  hl(0, "NvimTreeRootFolder", { fg = p.purple })
  hl(0, "NvimTreeSpecialFile", { fg = p.orange })
  hl(0, "NvimTreeGitDirty", { fg = p.yellow })
  hl(0, "NvimTreeGitNew", { fg = p.green })
  hl(0, "NvimTreeGitDeleted", { fg = p.red })
  hl(0, "NvimTreeIndentMarker", { fg = p.grey })

  -- neo-tree
  hl(0, "NeoTreeNormal", { fg = p.fg, bg = bg0 })
  hl(0, "NeoTreeNormalNC", { fg = p.fg, bg = bg0 })
  hl(0, "NeoTreeDirectoryIcon", { fg = p.blue })
  hl(0, "NeoTreeDirectoryName", { fg = p.green })
  hl(0, "NeoTreeRootName", { fg = p.purple, bold = true })
  hl(0, "NeoTreeFileName", { fg = p.fg })
  hl(0, "NeoTreeGitAdded", { fg = p.green })
  hl(0, "NeoTreeGitModified", { fg = p.yellow })
  hl(0, "NeoTreeGitDeleted", { fg = p.red })
  hl(0, "NeoTreeGitUntracked", { fg = p.orange })

  -- indent-blankline
  hl(0, "IblIndent", { fg = p.bg4 })
  hl(0, "IblScope", { fg = p.grey })

  -- vim-illuminate
  hl(0, "IlluminatedWordText", { underline = true })
  hl(0, "IlluminatedWordRead", { underline = true })
  hl(0, "IlluminatedWordWrite", { underline = true })

  -- lazy.nvim
  hl(0, "LazyH1", { fg = p.bg0, bg = p.green, bold = true })
  hl(0, "LazyButton", { fg = p.fg, bg = p.bg3 })
  hl(0, "LazyButtonActive", { fg = p.bg0, bg = p.blue, bold = true })
  hl(0, "LazySpecial", { fg = p.purple })

  -- which-key
  hl(0, "WhichKey", { fg = p.red })
  hl(0, "WhichKeyGroup", { fg = p.orange })
  hl(0, "WhichKeyDesc", { fg = p.blue })
  hl(0, "WhichKeySeparator", { fg = p.green })

  -- gitsigns
  hl(0, "GitGutterAdd", { fg = p.green, bg = bg1 })
  hl(0, "GitGutterChange", { fg = p.blue, bg = bg1 })
  hl(0, "GitGutterDelete", { fg = p.red, bg = bg1 })
  hl(0, "GitGutterChangeDelete", { fg = p.purple, bg = bg1 })

  -- markdown
  hl(0, "markdownH1", { fg = p.red, bold = true })
  hl(0, "markdownH2", { fg = p.orange, bold = true })
  hl(0, "markdownH3", { fg = p.yellow, bold = true })
  hl(0, "markdownH4", { fg = p.green, bold = true })
  hl(0, "markdownH5", { fg = p.blue, bold = true })
  hl(0, "markdownH6", { fg = p.purple, bold = true })
  hl(0, "markdownUrl", { fg = p.blue, underline = true })
  hl(0, "markdownItalic", { italic = true })
  hl(0, "markdownBold", { bold = true })
  hl(0, "markdownItalicDelimiter", { fg = p.grey, italic = true })
  hl(0, "markdownCode", { fg = p.green })
  hl(0, "markdownCodeBlock", { fg = p.green })
  hl(0, "markdownCodeDelimiter", { fg = p.green })
  hl(0, "markdownBlockquote", { fg = p.grey })
  hl(0, "markdownListMarker", { fg = p.red })
  hl(0, "markdownOrderedListMarker", { fg = p.red })
  hl(0, "markdownRule", { fg = p.purple })
  hl(0, "markdownHeadingRule", { fg = p.grey })
  hl(0, "markdownLinkText", { fg = p.red })
  hl(0, "markdownHeadingDelimiter", { fg = p.grey })
end

return M
